### ISSUE TITLE
consider limiting acceleration of swerve drive

### ISSUE THREAD

**Issue by gcschmit** [HuskieRobotics/3061-lib#13]

**Comment by gcschmit** [comment]
Yes, this is an idea requested by the team's driver for tele-op.

The idea was to use the slew rate limit to the velocities corresponding to the joysticks and not individual swerve modules. This should avoid issues related to different modules being limited differently.

We'll see how it goes....

**Comment by randomstring** [comment]
In general adding lag to driver inputs is a Bad Idea (TM). The SDS serve modules are fast. They are very twitchy to drive. We use the L2s (I can't imagine using L3s, and L1s might be a liability for autonomous). At the start of the season we just tuned the max driver input down to 60% and slowly increased it through the season as the driver got more confidence. We ran at 80% max driver input for most of the season, and not until districts did we take the cap off and go to 100%. 

We also tune the max driver input down when we train new drivers (and mentors).

**Comment by gcschmit** [comment]
I renamed the issue to no longer assume a particular solution. Spectrum takes a somewhat different approach to limiting acceleration:

https://github.com/Spectrum3847/SpectrumLib/blob/main/src/main/java/frc/SpectrumLib/swerve/SwerveUtil.java

**Comment by gcschmit** [comment]
Fixed in #36
