### ISSUE TITLE
add support to disable vision subsystem

### ISSUE THREAD

**Issue by gcschmit** [HuskieRobotics/3061-lib#14]
This is useful in case the camera is moved during a match and starts returning invalid information.

**Comment by yoyoconnor** [comment]
I don't see a vision subsystem in either 3061-lib or 2023 software so i am unsure of how to write code to disable a system that doesnt currently exist

**Comment by gcschmit** [comment]
In addition, due to how to pose estimator is implemented, if the vision subsystem is disabled, the pose estimator should be reset with a rotation from the gyro as the current pose rotation may be off and won't be adjusted as the gyro differences have been consistently correct.

**Comment by yoyoconnor** [comment]
branch has been merge requested
