### ISSUE TITLE
add Alerts for various situations

### ISSUE THREAD

**Issue by gcschmit** [HuskieRobotics/3061-lib#3]
Using Mechanical Advantage's Alert class which displays on Shuffleboard, add alerts for the following additional scenarios:

- no joystick(s)
- no xBox controller
- no control panel (button/switch panel)
- low battery
- FMS connected

(These are the alerts that Spectrum creates. Refer to their [2022 code](https://github.com/Spectrum3847/Infrared-2022) for examples.)

**Comment by admodi** [comment]
not going to implement low battery and FMS connected
