### ISSUE TITLE
Autonomous mode velocity limits  

### ISSUE THREAD

**Issue by martygubow** [HuskieRobotics/3061-lib#32]
I found an issue with autonomous velocity limits set in PathPlanner.   I believe it should be set as follows in RobotContainer. 
    List<PathPlannerTrajectory> auto1Paths =
        PathPlanner.loadPathGroup(
            "testPaths1",
            new PathConstraints(
                AUTO_MAX_SPEED_METERS_PER_SECOND, AUTO_MAX_ACCELERATION_METERS_PER_SECOND_SQUARED));

**Comment by gcschmit** [comment]
The loadPathGroup method is overloaded. The code that you propose would work fine as it would apply the path constraints to all paths in the group. The code currently in the 3061-lib has the same effect. The implementation of the loadPathGroup method currently invoked by 3061-lib has the following implementation:

```
public static List<PathPlannerTrajectory> loadPathGroup(
      String name, double maxVel, double maxAccel) {
    return loadPathGroup(name, false, new PathConstraints(maxVel, maxAccel));
  }
```

The advantage of using the overloaded method that takes a PathConstraints object is that you can pass multiple PathConstraints objects as arguments. Each one is mapped to the corresponding path in the group. So, for example, you can have some paths in the group with a lower maximum velocity than others. (We may use this feature to drive over the cable carrier at a slower speed.)
