### ISSUE TITLE
(Question) Invert single steer motor

### ISSUE THREAD

**Issue by aidenm05** [HuskieRobotics/3061-lib#35]
How would i make a single steer motor on my swerve chassis un inverted  while keeping the rest inverted on mk4i imodules

**Comment by gcschmit** [comment]
This should not be needed. Either all of the modules should be inverted or none. What I think is most likely is that when determining the offsets for the wheels, the bevel gears weren't all facing the same direction (most likely). More details are available in the [Tuning](https://github.com/HuskieRobotics/3061-lib#tuning) section of the README.

**Comment by aidenm05** [comment]
Our swerve is configured with MK four I swerve modules, however, due to a
air by our mechanical team, we have had to make two of the motors facing
upwards. These two motors are our front left steer and our front right
drive.

**Comment by gcschmit** [comment]
That isn't currently supported in the code. You could modify the SwerveModuleIOTalonFX class to set the various inverted variables based on the moduleNumber parameter passed to the constructor.

**Comment by aidenm05** [comment]
ok i can try to to do something like that
