### ISSUE TITLE
add "code loading" LED animation

### ISSUE THREAD

**Issue by gcschmit** [HuskieRobotics/3061-lib#75]
Add an LED animation that starts while the code is still loading. Refer to [Mechanical Advantage's approach](https://github.com/Mechanical-Advantage/RobotCode2023/blob/f0c26dc20e0f324a2093a4c81c687d41a120a07d/src/main/java/org/littletonrobotics/frc2023/subsystems/leds/Leds.java#L90-L103) for this feature. This is useful because our code takes a long time to load and an LED animation is reassuring that progress is being made.

**Comment by Madhusri02** [comment]
i shall do this

**Comment by gcschmit** [comment]
Sorry, we missed closing this issue when #82 was pulled into main. This is now implemented.
